# Generated by Django 2.1.3 on 2018-11-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo', models.CharField(max_length=254)),
                ('motivo', models.CharField(max_length=254)),
                ('imagen', models.FileField(blank=True, default=None, null=True, upload_to='storage/images/')),
            ],
        ),
    ]
